- name: create custom script
  template:
    src: "{{ item.file }}"
    dest: "{{ redmine_script_dir }}/{{ item.remote_name | default( item.file | basename ) }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_user }}"
    mode: "{{ item.mode | default( '0700' ) }}"
  loop: "{{ redmine_custom_script_files | default([]) | selectattr('removed', 'undefined') | list }}"
- name: remove custom script
  file:
    path: "{{ redmine_script_dir }}/{{ item.remote_name | default( item.file | basename ) }}"
    state: absent
  loop: "{{ redmine_custom_script_files | default([]) | selectattr('removed', 'defined') | list }}"
