---
- name: create import admin stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/admin.yml"
  vars:
    redmine_import_data: "{{ redmine_admin | default({}) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_admin
- name: create import issue status stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/status.yml"
  vars:
    redmine_import_data: "{{ redmine_issue_statuses | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_issue_status
- name: create import tracker stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/tracker.yml"
  vars:
    redmine_import_data: "{{ redmine_trackers | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_tracker
- name: create import redmine stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/setting.yml"
  vars:
    redmine_import_data: "{{ redmine_settings | default({}) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_setting
- name: create import role stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/role.yml"
  vars:
    redmine_import_data: "{{ redmine_roles | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_role
- name: create import issue custom field stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/issue_custom_field.yml"
  vars:
    redmine_import_data: "{{ redmine_issue_custom_fields | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_issue_custom_field
- name: create import project custom field stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/project_custom_field.yml"
  vars:
    redmine_import_data: "{{ redmine_project_custom_fields | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_project_custom_field
- name: create import user custom field stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/user_custom_field.yml"
  vars:
    redmine_import_data: "{{ redmine_user_custom_fields | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_user_custom_field
- name: create import priority stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/priority.yml"
  vars:
    redmine_import_data: "{{ redmine_priorities | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_priority
- name: create import document category stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/document_category.yml"
  vars:
    redmine_import_data: "{{ redmine_document_categories | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_document_category
- name: create import time entry activity stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/time_entry_activity.yml"
  vars:
    redmine_import_data: "{{ redmine_time_entry_activities | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_time_entry_activity
- name: create import workflow stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/workflow.yml"
  vars:
    redmine_import_data: "{{ redmine_workflows | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_workflow
- name: create import user stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/user.yml"
  vars:
    redmine_import_data: "{{ redmine_users | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_user
- name: create import group stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/group.yml"
  vars:
    redmine_import_data: "{{ redmine_groups | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_group
- name: create import project stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/project.yml"
  vars:
    redmine_import_data: "{{ redmine_projects | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_project
- name: create import view customize stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/view_customize.yml"
  vars:
    redmine_import_data: "{{ redmine_view_customize | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_view_customize
- name: create import issue templates stting files
  template:
    src: import_setting.yml.j2
    dest: "{{ redmine_home }}/tmp/import/issue_template.yml"
  vars:
    redmine_import_data: "{{ redmine_issue_templates | default([]) }}"
  when: |
    generate_token_result is changed
    or
    redmine_reimport_all
    or
    redmine_reimport_issue_templates
- name: update redmine settings
  shell: "bundle exec rails r {{ redmine_home }}/tmp/import.rb"
  args:
    chdir: "{{ redmine_home }}"

