---
- name: Setup redmine
  become: true
  become_user: "{{ redmine_user }}"
  environment:
    RAILS_ENV: "{{ redmine_mode }}"
    REDMINE_LANG: "{{ redmine_lang }}"
  block:
    - name: Checkout Redmine
      ansible.builtin.git:
        repo: "{{ redmine_repo }}"
        dest: "{{ redmine_home }}"
        version: "{{ redmine_version }}"
      register: git_result
    - name: Import setting task
      ansible.builtin.import_tasks:
        file: setting.yml
    - name: Execute bundle update
      ansible.builtin.command:
        cmd: bundle update
        chdir: "{{ redmine_home }}"
      when: git_result is changed
    - name: Create secret token
      ansible.builtin.command:
        cmd: bundle exec rake generate_secret_token
        chdir: "{{ redmine_home }}"
        creates: "{{ redmine_home }}/config/initializers/secret_token.rb"
      register: generate_token_result
    - name: Migrate database
      ansible.builtin.command:
        cmd: bundle exec rake db:migrate
        chdir: "{{ redmine_home }}"
      notify: restart redmine
      when: git_result is changed or db_config_result is changed
    - name: Load default data
      ansible.builtin.command:
        cmd: bundle exec rake redmine:load_default_data
        chdir: "{{ redmine_home }}"
      when:
        - generate_token_result is changed
        - redmine_restore_files is undefined
        - not redmine_skip_load_default_data
    - name: Import restore task
      ansible.builtin.import_tasks:
        file: restore.yml
    - name: Import theme task
      ansible.builtin.import_tasks:
        file: theme.yml
    - name: Import plugin task
      ansible.builtin.import_tasks:
        file: plugin.yml
    - name: clear cache
      ansible.builtin.command:
        cmd: bundle exec rake tmp:cache:clear
        chdir: "{{ redmine_home }}"
      when: redmine_cache_clear | default(false)
    - name: Create setting file directory
      ansible.builtin.file:
        path: "{{ redmine_home }}/tmp/import"
        state: directory
        mode: "0755"

    - name: Import import data task
      ansible.builtin.import_tasks:
        file: import.yml
      when: |
        generate_token_result is changed
        or
        redmine_reimport | default(false)
