---
- name: Setup redmine
  become: true
  become_user: "{{ redmine_user }}"
  environment:
    RAILS_ENV: "{{ redmine_mode }}"
    REDMINE_LANG: "{{ redmine_lang }}"
  block:
    - name: Checkout Redmine
      ansible.builtin.git:
        repo: "{{ redmine_repo }}"
        dest: "{{ redmine_home }}"
        version: "{{ redmine_version }}"
      register: git_result
    - name: Import setting task
      ansible.builtin.import_tasks:
        file: setting.yml

    - name: Install/update gem packages
      community.general.bundler:
        gemfile: "{{ redmine_home }}/Gemfile"
        deployment_mode: "{{ redmine_mode == 'production' }}"
        exclude_groups: "{{ redmine_mode == 'production' | ternary(['development', 'test'], omit) }}"
        state: latest
        user_install: true
        chdir: "{{ redmine_home }}"

    - name: Create secret token
      ansible.builtin.command:
        cmd: bundle exec rake generate_secret_token
        chdir: "{{ redmine_home }}"
        creates: "{{ redmine_home }}/config/initializers/secret_token.rb"
      register: generate_token_result

    - name: Migrate database
      ansible.builtin.command:
        cmd: bundle exec rake db:migrate
        chdir: "{{ redmine_home }}"
      notify: restart redmine
      when: git_result is changed or db_config_result is changed
    - name: Load default data
      ansible.builtin.command:
        cmd: bundle exec rake redmine:load_default_data
        chdir: "{{ redmine_home }}"
      when:
        - generate_token_result is changed
        - redmine_restore_files is undefined
        - not redmine_skip_load_default_data
