---
- name: Create puma config file
  ansible.builtin.template:
    src: puma.rb.j2
    dest: "{{ redmine_root }}/config/puma.rb"
    mode: "0644"
  become: true
  become_user: "{{ redmine_user }}"
  notify: restart redmine
- name: Create/update envirnment file
  ansible.builtin.template:
    src: environment_file.j2
    dest: /etc/default/redmine
    mode: "0644"
  notify: restart redmine
- name: Create Redmine systemd unit file
  ansible.builtin.template:
    src: redmine.service.j2
    dest: /lib/systemd/system/redmine.service
    mode: "0644"
  notify: restart redmine
- name: Service Redmine is active and enable on system startup
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: redmine
    state: started
    enabled: true
- name: Create Sidekiq systemd unit file
  when: redmine_register_sidekiq_service
  block:
    - name: Create Sidekiq systemd unit file
      ansible.builtin.template:
        src: sidekiq.service.j2
        dest: /lib/systemd/system/sidekiq.service
        mode: "0644"
      notify: restart sidekiq
    - name: Service Sidekiq is active and enable on system startup
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: sidekiq
        state: started
        enabled: true
