---
- name: Create/update setting files
  become: true
  become_user: "{{ redmine_user }}"
  block:
    - name: Create bundler setting directory
      ansible.builtin.file:
        path: "{{ redmine_home }}/.bundle"
        state: directory
        mode: "0755"
    - name: Create//update bundler setting file
      ansible.builtin.template:
        src: bundle/config.j2
        dest: "{{ redmine_home }}/.bundle/config"
        mode: "0644"
    - name: Gemfile.localの自動設定
      when: redmine_gemfile_local_content is undefined
      block:
        - name: Find puma package on Gemfile
          ansible.builtin.command:
            cmd: grep puma Gemfile
            chdir: "{{ redmine_home }}"
          changed_when: false
          register: puma_version_result
        - name: Set Gemfile.local setting value variable
          ansible.builtin.set_fact:
            redmine_gemfile_local_content: "{{ puma_version_result.stdout | trim }}"
    - name: Create/update Gemfile.local file
      ansible.builtin.template:
        src: Gemfile.local.j2
        dest: "{{ redmine_home }}/Gemfile.local"
        mode: "0644"
    - name: Create/update database config file
      ansible.builtin.template:
        src: database.yml.j2
        dest: "{{ redmine_home }}/config/database.yml"
        mode: "0644"
      register: db_config_result
    - name: Create/update Redmine config file
      ansible.builtin.template:
        src: configuration.yml.j2
        dest: "{{ redmine_home }}/config/configuration.yml"
        mode: "0644"
      notify: restart redmine
    - name: Create/update additional environment file
      ansible.builtin.template:
        src: additional_environment.rb.j2
        dest: "{{ redmine_home }}/config/additional_environment.rb"
        mode: "0644"
      notify: restart redmine
