---
redmine_db_cfg:
  production:
    adapter: mysql2
    database: redmine_prod
    host: localhost
    username: redmine_prod_user
    password: redmine_prod_password
    encoding: utf8mb4
  development:
    adapter: mysql2
    database: redmine_dev
    host: localhost
    username: redmine_dev_user
    password: redmine_dev_password
    encoding: utf8mb4
  test:
    adapter: mysql2
    database: redmine_test
    host: localhost
    username: redmine_test_user
    password: redmine_test_password
    encoding: utf8mb4

redmine_puma_extra_cfg: |
  port 3000
