---
redmine_db_cfg:
  production:
    adapter: mysql2
    database: redmine_prod
    host: localhost
    username: redmine_prod_user
    password: redmine_prod_password
    encoding: utf8mb4
  development:
    adapter: mysql2
    database: redmine_dev
    host: localhost
    username: redmine_dev_user
    password: redmine_dev_password
    encoding: utf8mb4
  test:
    adapter: mysql2
    database: redmine_test
    host: localhost
    username: redmine_test_user
    password: redmine_test_password
    encoding: utf8mb4

redmine_cfg:
  default:
    sudo_mode: true
    sudo_mode_timeout: 15

redmine_themes:
  - name: PurpleMine2
    repo: https://github.com/mrliptontea/PurpleMine2.git
  - name: gitmike
    repo: https://github.com/makotokw/redmine-theme-gitmike.git

redmine_plugins:
  - name: view_customize
    repo: https://github.com/onozaty/redmine-view-customize.git
    directory: view_customize
  - name: issue_templates
    repo: https://github.com/agileware-jp/redmine_issue_templates.git
  - name: slack
    repo: https://github.com/cat-in-136/redmine-slack.git
    version: evolved
  - name: dashboard
    repo: https://github.com/jgraichen/redmine_dashboard.git
    version: main
  - name: drawio
    repo: https://github.com/mikitex70/redmine_drawio.git
  - name: redmica_ui_extension
    repo: https://github.com/redmica/redmica_ui_extension.git
    directory: redmica_ui_extension
    version: master
  - name: message_customize
    repo: https://github.com/ishikawa999/redmine_message_customize.git
  - name: dmsf
    repo: https://github.com/danmunn/redmine_dmsf.git
    required_packages:
      # CGI search interface and indexers using Xapian
      - xapian-omega
      # Xapian 検索エンジンライブラリ用開発ファイル
      - libxapian-dev
      # Xapian search engine interface for Ruby
      - ruby-xapian
      # Converts MS Word files to text, PS, PDF and XML
      - antiword
      # text extractor for MS-Office files
      - catdoc
      # PDF 向けユーティリティ
      - poppler-utils
      # Universally Unique Identifier Command-Line Tool
      - uuid
    cron_job:
      cmd: cd {{ redmine_home }}/plugins && /usr/bin/ruby redmine_dmsf/extra/xapian_indexer.rb -v
      minute: 10
  - name: additionals
    repo: https://github.com/AlphaNodes/additionals.git
    directory: additionals
    version: stable
  - name: sudo
    repo: https://github.com/AlphaNodes/redmine_sudo.git
    version: stable
  ## unverified plugin
  - name: saml
    repo: https://github.com/AlphaNodes/redmine_saml.git
    version: main
    custom_setting_file:
      path: "{{ redmine_home }}/config/initializers/saml.rb"
      content: |
        # frozen_string_literal: true
        require Rails.root.join('plugins/redmine_saml/lib/redmine_saml')
        require Rails.root.join('plugins/redmine_saml/lib/redmine_saml/base')
        RedmineSaml::Base.configure do |config|
          config.saml = {
            # Redmine callback URL
            assertion_consumer_service_url: "http://redmine.example.com#{RedmineSaml::CALLBACK_PATH}",
            # The issuer name / entity ID. Must be an URI as per SAML 2.0 spec.
            # sp_entity_id: 'http://redmine.example.com/auth/saml/metadata' or
            sp_entity_id: "http://redmine.example.com#{RedmineSaml::METADATA_PATH}",
            # The SLS (logout) callback URL
            single_logout_service_url: "http://redmine.example.com#{RedmineSaml::LOGOUT_SERVICE_PATH}",
            # SSO login endpoint
            idp_sso_service_url: 'https://sso.desarrollo.unlp.edu.ar/saml2/idp/SSOService.php',
            # SSO SSL certificate SHA-1 fingerprint
            idp_cert_fingerprint: 'certificate fingerprint',
            # Alternatively, specify the full certifiate:
            # idp_cert: "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
            name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
            # Optional signout URL, not supported by all identity providers
            signout_url: 'https://sso.example.com/saml2/idp/SingleLogoutService.php?ReturnTo=',
            idp_slo_service_url: 'https://sso.example.com/saml2/idp/SingleLogoutService.php',
            # Which redmine field is used as name_identifier_value for SAML logout
            name_identifier_value: 'mail',
            # overwrite mapping seperator, if required
            # attribute_mapping_sep: '|',
            attribute_mapping: {
              # How will we map attributes from SSO to redmine attributes
              # using either urn:oid:identifier, or friendly names, e.g.
              # mail: 'extra|raw_info|urn:oid:0.9.2342.19200300.100.1.3'
              # or
              # mail: 'extra|raw_info|email'
              #
              # Edit defaults below to match your attributes
              login: 'extra|raw_info|username',
              mail: 'extra|raw_info|email',
              firstname: 'extra|raw_info|firstname',
              lastname: 'extra|raw_info|firstname',
              admin: 'extra|raw_info|admin'
            }
          }
          config.on_login do |omniauth_hash, user|
            # Implement any hook you want here
          end
        end

redmine_puma_extra_cfg: |
  port 3000
