---
redmine_db_cfg:
  production:
    adapter: mysql2
    database: redmine
    host: localhost
    username: redmine_user
    password: redmine_password
    encoding: utf8mb4
  development:
    adapter: mysql2
    database: redmine
    host: localhost
    username: redmine_user
    password: redmine_password
    encoding: utf8mb4
  test:
    adapter: mysql2
    database: redmine
    host: localhost
    username: redmine_user
    password: redmine_password
    encoding: utf8mb4
