---
logrotate_settings:
  - name: redmine
    paths:
      - /opt/redmine/log/*.log*
    frequency: daily
    missingok: true
    rotate: 14
    compress: true
    delaycompress: true
    notifempty: true
    create: true
    create_mode: "0640"
    create_user: redmine
    create_group: redmine

redmine_db_cfg:
  production:
    adapter: mysql2
    database: redmine_prod
    host: localhost
    username: redmine_prod_user
    password: redmine_prod_password
    encoding: utf8mb4
  development:
    adapter: mysql2
    database: redmine_dev
    host: localhost
    username: redmine_dev_user
    password: redmine_dev_password
    encoding: utf8mb4
  test:
    adapter: mysql2
    database: redmine_test
    host: localhost
    username: redmine_test_user
    password: redmine_test_password
    encoding: utf8mb4

redmine_cfg:
  default:
    sudo_mode: true
    sudo_mode_timeout: 15

redmine_themes:
  - name: PurpleMine2
    repo: https://github.com/mrliptontea/PurpleMine2.git
  - name: gitmike
    repo: https://github.com/makotokw/redmine-theme-gitmike.git

redmine_plugins:
  - name: view_customize
    repo: https://github.com/onozaty/redmine-view-customize.git
    directory: view_customize
  - name: issue_templates
    repo: https://github.com/agileware-jp/redmine_issue_templates.git
  - name: slack
    repo: https://github.com/cat-in-136/redmine-slack.git
    version: evolved
  - name: dashboard
    repo: https://github.com/jgraichen/redmine_dashboard.git
    version: main
  - name: drawio
    repo: https://github.com/mikitex70/redmine_drawio.git
  - name: redmica_ui_extension
    repo: https://github.com/redmica/redmica_ui_extension.git
    directory: redmica_ui_extension
    version: master
  - name: additionals
    repo: https://github.com/AlphaNodes/additionals.git
    directory: additionals
    version: stable
  - name: sudo
    repo: https://github.com/AlphaNodes/redmine_sudo.git
    version: stable
  - name: dmsf
    repo: https://github.com/danmunn/redmine_dmsf.git
    required_packages:
      # CGI search interface and indexers using Xapian
      - xapian-omega
      # Xapian 検索エンジンライブラリ用開発ファイル
      - libxapian-dev
      # Xapian search engine interface for Ruby
      - ruby-xapian
      # Converts MS Word files to text, PS, PDF and XML
      - antiword
      # text extractor for MS-Office files
      - catdoc
      # PDF 向けユーティリティ
      - poppler-utils
      # Universally Unique Identifier Command-Line Tool
      - uuid
    cron_job:
      cmd: cd {{ redmine_home }}/plugins && /usr/bin/ruby redmine_dmsf/extra/xapian_indexer.rb -v
      minute: 10
  - name: message_customize
    repo: https://github.com/farend/redmine_message_customize.git

##
redmine_puma_extra_cfg: |
  port 3000
