# code: language=ansible
---
- name: restart redmine
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: redmine
    state: restarted
- name: reload redmine
  ansible.builtin.systemd_service:
    name: redmine
    state: reloaded
- name: restart sidekiq
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: sidekiq
    state: restarted
