---
- name: Install database dependency packages(MariaDB)
  ansible.builtin.apt:
    name: "{{ redmine_mysql2_dependency_packages }}"
- name: Create database
  community.mysql.mysql_db:
    name: "{{ redmine_db_cfg[redmine_mode]['database'] }}"
    encoding: "{{ redmine_db_cfg[redmine_mode]['encoding'] | default('utf8mb4') }}"
    login_unix_socket: "{{ mariadb_unix_socket_path | default('/run/mysqld/mysqld.sock') }}"
- name: Create database user
  community.mysql.mysql_user:
    name: "{{ redmine_db_cfg[redmine_mode]['username'] }}"
    password: "{{ redmine_db_cfg[redmine_mode]['password'] }}"
    host: "{{ item }}"
    priv: "{{ redmine_db_cfg[redmine_mode]['database'] }}.*:ALL"
    login_unix_socket: "{{ mariadb_unix_socket_path | default('/run/mysqld/mysqld.sock') }}"
  loop:
    - localhost
    - 127.0.0.1
  no_log: true
- name: Create mysql connection setting file
  community.general.ini_file:
    path: ~/.my.cnf
    create: true
    section: client
    option: "{{ item.key | replace('_', '-') }}"
    value: "{{ item.value | string }}"
    mode: "0640"
  loop: "{{ redmine_database_setting | dict2items }}"
  vars:
    redmine_database_setting:
      host: "{{ redmine_db_cfg[redmine_mode]['host'] }}"
      database: "{{ redmine_db_cfg[redmine_mode]['database'] }}"
      user: "{{ redmine_db_cfg[redmine_mode]['username'] }}"
      password: "{{ redmine_db_cfg[redmine_mode]['password'] }}"
      default_character_set: "{{ redmine_db_cfg[redmine_mode]['encoding'] | default('utf8mb4') }}"
  become: true
  become_user: "{{ redmine_user }}"
  no_log: true
