---
- name: Install database dependency packages(PostgreSQL)
  ansible.builtin.apt:
    name: "{{ redmine_postgresql_dependency_packages }}"
- name: Setup database
  become: true
  become_user: postgres
  block:
    - name: Create database user
      community.postgresql.postgresql_user:
        name: "{{ redmine_db_cfg[redmine_mode]['username'] }}"
        password: "{{ redmine_db_cfg[redmine_mode]['password'] }}"
    - name: Create database
      community.postgresql.postgresql_db:
        name: "{{ redmine_db_cfg[redmine_mode]['database'] }}"
        owner: "{{ redmine_db_cfg[redmine_mode]['username'] }}"
        encoding: "{{ redmine_db_cfg[redmine_mode]['encoding'] | default('UTF8') }}"
