---
- name: Converge
  hosts: all
  become: true
  environment:
    IMPORT_DATA_FILE_NO_DELETE: "1"
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
      changed_when: false
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
      changed_when: false
  roles:
    - role: common
    - role: logrotate
    - role: mariadb
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: Copy import test file
      ansible.builtin.copy:
        src: files/import_test.rb
        dest: /opt/redmine/test/integration/
        owner: redmine
        group: redmine
        mode: '0644'
