---
- name: Converge
  hosts: all
  roles:
    - name: common
    - name: mariadb
  tasks:
    - name: "Include role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
