---
- name: Verify
  hosts: all
  gather_facts: false
  check_mode: true
  become: true
  tasks:
    ## ユーザーのテスト
    - name: Add user check
      ansible.builtin.user:
        name: redmine
      register: result
    - name: Assert user
      ansible.builtin.assert:
        that: result is not changed
    ## グループのテスト
    - name: Add group check
      ansible.builtin.group:
        name: redmine
      register: result
    - name: Assert group
      ansible.builtin.assert:
        that: result is not changed
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['ruby']
          - ansible_facts.packages['ruby-dev']
          - ansible_facts.packages['rubygems-integration']
          - ansible_facts.packages['acl']
          - ansible_facts.packages['git']
    - name: Check theme directory
      ansible.builtin.stat:
        path: /opt/redmine/themes
      register: redmine_theme_dir_result
    - name: Test theme
      block:
        - name: Overwrite redmine_theme_dir variable
          ansible.builtin.set_fact:
            redmine_theme_dir: "/opt/redmine/{{ 'themes' if redmine_theme_dir_result.stat.exists else 'public/themes' }}"
        - name: Check installed PurpleMine2 theme
          ansible.builtin.stat:
            path: "{{ redmine_theme_dir }}/PurpleMine2"
          register: check_installed_theme_result
        - name: Assert installed PurpleMine2 theme
          ansible.builtin.assert:
            that: check_installed_theme_result.stat.exists
        - name: Check installed gitmike theme
          ansible.builtin.stat:
            path: "{{ redmine_theme_dir }}/gitmike"
          register: check_installed_theme_result
        - name: Assert installed gitmike theme
          ansible.builtin.assert:
            that: check_installed_theme_result.stat.exists
        - name: Check installed farend_fancy theme
          ansible.builtin.stat:
            path: "{{ redmine_theme_dir }}/farend_fancy"
          register: check_installed_theme_result
        - name: Assert installed farend_fancy theme
          ansible.builtin.assert:
            that: check_installed_theme_result.stat.exists
        - name: Check installed farend_basic theme
          ansible.builtin.stat:
            path: "{{ redmine_theme_dir }}/farend_basic"
          register: check_installed_theme_result
        - name: Assert installed farend_basic theme
          ansible.builtin.assert:
            that: check_installed_theme_result.stat.exists
        - name: Check installed bleuclair theme
          ansible.builtin.stat:
            path: "{{ redmine_theme_dir }}/bleuclair"
          register: check_installed_theme_result
        - name: Assert installed bleuclair theme
          ansible.builtin.assert:
            that: check_installed_theme_result.stat.exists
    - name: Test plugin
      block:
        - name: Check installed view_customize plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/view_customize
          register: check_installed_plugin_result
        - name: Assert installed view_customize plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_issue_templates plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_issue_templates
          register: check_installed_plugin_result
        - name: Assert installed redmine_issue_templates plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_messenger plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_messenger
          register: check_installed_plugin_result
        - name: Assert installed redmine_slack plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_dashboard plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_dashboard
          register: check_installed_plugin_result
        - name: Assert installed redmine_dashboard plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_drawio plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_drawio
          register: check_installed_plugin_result
        - name: Assert installed redmine_drawio plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmica_ui_extension plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmica_ui_extension
          register: check_installed_plugin_result
        - name: Assert installed redmica_ui_extension plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed additionals plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/additionals
          register: check_installed_plugin_result
        - name: Assert installed additionals plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_message_customize plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_message_customize
          register: check_installed_plugin_result
        - name: Assert installed redmine_message_customize plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_sudo plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_sudo
          register: check_installed_plugin_result
        - name: Assert installed redmine_sudo plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
        - name: Check installed redmine_dmsf plugin
          ansible.builtin.stat:
            path: /opt/redmine/plugins/redmine_dmsf
          register: check_installed_plugin_result
        - name: Assert installed redmine_dmsf plugin
          ansible.builtin.assert:
            that: check_installed_plugin_result.stat.exists
    - name: Check import task
      ansible.builtin.stat:
        path: /opt/redmine/lib/tasks/import.rake
      register: import_task_result
    - name: Assert import task
      ansible.builtin.assert:
        that: import_task_result.stat.exists
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['redmine.service']
          - ansible_facts.services['redmine.service']['state'] == 'running'
          - ansible_facts.services['redmine.service']['status'] == 'enabled'
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 3000 in listen_tcp_posts
