---
redmine_plugins:
  - name: view_customize
    repo: https://github.com/onozaty/redmine-view-customize.git
    directory: view_customize
  - name: issue_templates
    repo: https://github.com/agileware-jp/redmine_issue_templates.git
  - name: slack
    repo: https://github.com/cat-in-136/redmine-slack.git
    version: evolved
  - name: dashboard
    repo: https://github.com/jgraichen/redmine_dashboard.git
    version: main
  - name: drawio
    repo: https://github.com/mikitex70/redmine_drawio.git
  - name: redmica_ui_extension
    repo: https://github.com/redmica/redmica_ui_extension.git
    directory: redmica_ui_extension
    version: master
  - name: additionals
    repo: https://github.com/AlphaNodes/additionals.git
    directory: additionals
    version: 3.0.9
  - name: sudo
    repo: https://github.com/AlphaNodes/redmine_sudo.git
    version: stable
  - name: dmsf
    repo: https://github.com/danmunn/redmine_dmsf.git
    required_packages:
      # CGI search interface and indexers using Xapian
      - xapian-omega
      # Xapian 検索エンジンライブラリ用開発ファイル
      - libxapian-dev
      # Xapian search engine interface for Ruby
      - ruby-xapian
      # Converts MS Word files to text, PS, PDF and XML
      - antiword
      # text extractor for MS-Office files
      - catdoc
      # PDF 向けユーティリティ
      - poppler-utils
      # Universally Unique Identifier Command-Line Tool
      - uuid
    cron_job:
      cmd: cd {{ redmine_home }}/plugins && /usr/bin/ruby redmine_dmsf/extra/xapian_indexer.rb -v
      minute: 10
  - name: message_customize
    repo: https://github.com/farend/redmine_message_customize.git
