---
redmine_plugins:
  view_customize:
    repo: https://github.com/onozaty/redmine-view-customize.git
  redmine_issue_templates:
    repo: https://github.com/agileware-jp/redmine_issue_templates.git
  redmine_slack:
    repo: https://github.com/cat-in-136/redmine-slack.git
    version: evolved
  redmine_dashboard:
    repo: https://github.com/jgraichen/redmine_dashboard.git
    version: main
  redmine_drawio:
    repo: https://github.com/mikitex70/redmine_drawio.git
  redmica_ui_extension:
    repo: https://github.com/redmica/redmica_ui_extension.git
    version: master
  additionals:
    repo: https://github.com/AlphaNodes/additionals.git
    version: 3.0.9
  redmine_sudo:
    repo: https://github.com/AlphaNodes/redmine_sudo.git
    version: stable
  redmine_dmsf:
    repo: https://github.com/danmunn/redmine_dmsf.git
    required_packages:
      # CGI search interface and indexers using Xapian
      - xapian-omega
      # Xapian 検索エンジンライブラリ用開発ファイル
      - libxapian-dev
      # Xapian search engine interface for Ruby
      - ruby-xapian
      # Converts MS Word files to text, PS, PDF and XML
      - antiword
      # text extractor for MS-Office files
      - catdoc
      # PDF 向けユーティリティ
      - poppler-utils
      # Universally Unique Identifier Command-Line Tool
      - uuid
    cron_job:
      cmd: cd {{ redmine_root }}/plugins && /usr/bin/ruby redmine_dmsf/extra/xapian_indexer.rb -v
      minute: 10
  redmine_message_customize:
    repo: https://github.com/farend/redmine_message_customize.git
