---
common_install_utilities:
  - tig
  - jq
  - silversearcher-ag
  - eza
  - vnstati
  - glances
  - rclone

## --------------------
## Redmineのバージョン(ブランチ名)
## --------------------
redmine_version: 5.1-stable
