---
- name: Create/update additional environment file
  ansible.builtin.blockinfile:
    path: "{{ redmine_root }}/config/additional_environment.rb"
    marker: "# {mark} customize_message ANSIBLE MANAGED BLOCK"
    content: config.paths['config/locales'] = ['config/locales', '{{ redmine_customize_message_dir }}']
    mode: "0644"
    create: true
  notify: restart redmine
- name: Create redmine customize locales directory
  ansible.builtin.file:
    path: "{{ redmine_root }}/{{ redmine_customize_message_dir }}"
    state: directory
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    mode: "0755"
- name: Create customize massege files
  ansible.builtin.template:
    src: customize/lang.yml.j2
    dest: "{{ redmine_root }}/{{ redmine_customize_message_dir }}/{{ custom_message.lang }}.yml"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    mode: "0644"
  vars:
    custom_message_setting: "{{ {custom_message.lang: custom_message.value} }}"
  loop: "{{ redmine_customize_message | dict2items(key_name='lang') }}"
  loop_control:
    loop_var: custom_message
    label: "{{ custom_message.lang }}"
  notify: restart redmine
